InternshipManagementSystem/Controllers/FacultyCoordinatorModuleController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InternshipManagementSystem.Controllers
{
    [Authorize]
    public class FacultyCoordinatorModuleController : BaseController
    {
        String connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\user\Pictures\InMS\InternshipManagementSystem\App_Data\INMS.mdf;Integrated Security=True";

        [HttpGet]
        public ActionResult AssignSupervisorView(String id)
        {
            if (ViewBag.Role == "Student")
            {
                return RedirectToAction("Index", "Home");
            }
            List<Models.UserModel> alldetails = new List<Models.UserModel>();
            List<Models.UserModel> found = null;
            alldetails = GetStudentDetails();
            if (id == null)
            {
                ViewBag.Found = true;
                return View(alldetails);
            }
            else
            {
                id = id.ToLower();
                foreach (Models.UserModel user in alldetails)
                {
                    if (user.MatricID.ToLower().Contains(id))
                    {
                        if (found == null)
                        {
                            found = new List<Models.UserModel>();
                        }
                        found.Add(user);
                    }
                    else if (user.FullName.ToLower().Contains(id))
                    {
                        if (found == null)
                        {
                            found = new List<Models.UserModel>();
                        }
                        found.Add(user);
                    }
                    else if (user.State.ToLower().Contains(id))
                    {
                        if (found == null)
                        {
                            found = new List<Models.UserModel>();
                        }
                        found.Add(user);
                    }
                    else if (user.CompanyName.ToLower().Contains(id))
                    {
                        if (found == null)
                        {
                            found = new List<Models.UserModel>();
                        }
                        found.Add(user);
                    }
                    else if (user.FacultySupervisorName.ToLower().Contains(id))
                    {
                        if (found == null)
                        {
                            found = new List<Models.UserModel>();
                        }
                        found.Add(user);
                    }
                    else if (user.IndustrySupervisorName.ToLower().Contains(id))
                    {
                        if (found == null)
                        {
                            found = new List<Models.UserModel>();
                        }
                        found.Add(user);
                    }

                }
                if (found == null)
                {
                    ViewBag.Found = false;
                    return View();
                }
                else
                {
                    ViewBag.Found = true;
                    return View(found);
                }
            }
        }
        public List<Models.UserModel> GetStudentDetails()
        {
            Models.UserModel studentdetail = null;
            List<Models.UserModel> alldetails = new List<Models.UserModel>();
            int i;
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[User_Table] WHERE Roles = 'Student' ORDER BY Full_Name ASC", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                while (rd.Read())
                {
                    studentdetail = new Models.UserModel();
                    studentdetail.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    studentdetail.FullName = Convert.ToString(rd.GetSqlValue(4));
                    studentdetail.MatricID = Convert.ToString(rd.GetSqlValue(5));
                    studentdetail.State = Convert.ToString(rd.GetSqlValue(8));
                    studentdetail.CompanyName = Convert.ToString(rd.GetSqlValue(9));
                    studentdetail.FacultySupervisorName = Convert.ToString(rd.GetSqlValue(22));
                    studentdetail.IndustrySupervisorName = Convert.ToString(rd.GetSqlValue(23));
                    studentdetail.InternshipPeriodStart = Convert.ToString(rd.GetSqlValue(16));
                    studentdetail.InternshipPeriodEnd = Convert.ToString(rd.GetSqlValue(17));
                    alldetails.Add(studentdetail);
                }
            }
            for (i = 0; i < alldetails.Count; i++)
            {
                alldetails[i].Id = i + 1;
            }
            return alldetails;
        }
        [HttpGet]
        public ActionResult AssignSupervisorFormView(String fullname)
        {
            if (ViewBag.Role == "Student")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Student = fullname;
            Models.UserModel supervisors = new Models.UserModel();
            supervisors.Supervisorlist = GetFacultySupervisor();
            return View(supervisors);
        }

        public List<Models.UserModel> GetFacultySupervisor()
        {
            Models.UserModel model = null;
            List<Models.UserModel> supervisors = new List<Models.UserModel>();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[User_Table] WHERE Roles = 'Faculty Supervisor' ORDER BY Full_Name ASC", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                while (rd.Read())
                {
                    model = new Models.UserModel();
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.FullName = Convert.ToString(rd.GetSqlValue(4));
                    supervisors.Add(model);
                }
            }
            return supervisors;
        }
        [HttpPost]
        public ActionResult AssignSupervisor(Models.UserModel supervisor)
        {
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("UPDATE [dbo].[User_Table] SET F_Supervisor_Full_Name = '" + supervisor.FacultySupervisorName + "', F_Supervisor_Name = '" + GetUsernameByName(supervisor.FacultySupervisorName )+ "' WHERE Full_Name = '" + supervisor.FullName + "'", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                cn.Close();
            }
            return RedirectToAction("AssignSupervisorView");
        }
        public String GetUsernameByName(String fullname)
        {
            String username;
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT Username FROM [dbo].[User_Table] WHERE Full_Name = '" + fullname +"'", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                rd.Read();
                username = Convert.ToString(rd.GetSqlValue(0));
            }
            return username;
        }
    }
}

InternshipManagementSystem/Views/FacultyCoordinatorModule/AssignSupervisorFormView.cshtml
@model InternshipManagementSystem.Models.UserModel
@{
    ViewBag.Title = "AnnouncementFormView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--//banner -->
<!--/w3_short-->
<div class="services-breadcrumb_w3layouts">
    <div class="inner_breadcrumb">

        <ul class="short_w3ls" _w3ls>
            <li><a href="index.html">Home</a><span>|</span></li>
            <li>Assign Faculty</li>
        </ul>
    </div>
</div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Assign Faculty</h3>
</div>
<!--//w3_short-->
<!-- /inner_content -->
<div class="container" ">
    <div class=" col-lg-12 well">
        <div class="row">
            @using (Html.BeginForm("AssignSupervisor", "FacultyCoordinatorModule", FormMethod.Post, new { }))
            {
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right; text-align:right; width:550px;">
                            Student Name :
                        </div>
                        <div class="col-sm-8 form-group" style="text-align:left; width:350px;">
                            <label>@ViewBag.Student</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right; width:550px; ">
                            Faculty Supervisor :
                        </div>
                        <div class="col-sm-8 form-group" style="text-align:left; width:350px;">
                            @Html.DropDownListFor(model => model.FacultySupervisorName, new SelectList(Model.Supervisorlist, "FullName", "FullName"), "- -Select- -")
                            <br />
                            <br />
                            <br />
                            <br /><br /><br />
                        </div>

                    </div>
                    <div class="row" style="text-align:center;">
                        @Html.HiddenFor(model => (model.FullName))
                        <button style="margin-top: 20px;" type="submit" class="btn btn-lg btn-info">Assign Supervisor</button>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

<!-- //inner_content -->
<!-- footer -->
<div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

InternshipManagementSystem/Views/FacultyCoordinatorModule/AssignSupervisorView.cshtml
@model List<InternshipManagementSystem.Models.UserModel>
@Styles.Render("~/Content/viewlogbook.css")
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>

<!--//banner -->
<!--/w3_short-->
<div class="services-breadcrumb_w3layouts">
    <div class="inner_breadcrumb">

        <ul class="short_w3ls" _w3ls>
            <li><a href="index.html">Home</a><span>|</span></li>
            <li>Assign Faculty</li>
        </ul>
    </div>
</div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Assign Faculty</h3>
</div>
<!--//w3_short-->
<!-- /inner_content -->
<h2>Assign Faculty Supervisor</h2>
<div style="width: 100%; text-align:center; display:inline-block;">
    Keyword <input type="text" id="txtSearch" /><input type="button" id="btnSearch" value="Search" onclick="StartSearch();" />
    @if (ViewBag.Found == false)
    {
        <div style="color:red;display:inline-block;">No Result!</div>
    }
</div>
<br />
<br />
<script>
    function StartSearch() {
        var Text = document.getElementById('txtSearch').value;
        window.location.href = '/FacultyCoordinatorModule/AssignSupervisorView/' + Text;
    }
</script>

<table style="width:100%; border:2px solid black;">
    <thead style="display:block;">
        <tr>
            <th style="width:1%;text-align:center;">No</th>
            <th style="width:10%;text-align:center;">Matric ID</th>
            <th style="width:10%;text-align:center;">Name</th>
            <th style="width:10%;text-align:center;">Location</th>
            <th style="width:10%;text-align:center;">Company Name</th>
            <th style="width:10%;text-align:center;">Faculty Supervisor</th>
            <th style="width:11%;text-align:center;">Industrial Supervisor</th>
            <th style="width:10%;padding-left:60px;">Date</th>
        </tr>
    </thead>
    <tbody style="display:block; height:300px;overflow-y:auto;overflow-x:hidden;width:100%; border-top:2px solid black;">
        @if (ViewBag.Found == true)
            {
                foreach (var item in Model)
                {

                <tr>
                    <td style="width:2%;text-align:center;">@Html.Raw(item.Id)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(item.MatricID)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(item.FullName)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(item.State)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(item.CompanyName)</td>
                    @{
                        if (item.FacultySupervisorName == "Null")
                        {
                            <td style="width:10%;text-align:center;">
                                @Html.ActionLink("Assign", "AssignSupervisorFormView",
"FacultyCoordinatorModule", new { item.FullName }, new { })
                            </td>
                        }
                        else
                        {
                            <td style="width:10%;text-align:center;">@Html.Raw(item.FacultySupervisorName)</td>
                        }
                    }

                    <td style="width:10%;text-align:center;">@Html.Raw(item.IndustrySupervisorName)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(item.InternshipPeriodStart) - @Html.Raw(item.InternshipPeriodEnd)</td>
                </tr>

                            }
                        }
    </tbody>
</table>
<script>

    var $table = $('table.scroll'),
        $bodyCells = $table.find('tbody tr:first').children(),
        colWidth;

    // Adjust the width of thead cells when window resizes
    $(window).resize(function () {
        // Get the tbody columns width array
        colWidth = $bodyCells.map(function () {
            return $(this).width();
        }).get();

        // Set the width of thead columns
        $table.find('thead tr').children().each(function (i, v) {
            $(v).width(colWidth[i]);
        });
    }).resize();
</script>
<!-- //mid-services -->
<!-- //inner_content -->
<!-- footer -->
<!-- //inner_content -->
<!-- footer -->
<div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>