InternshipManagementSystem/Controllers/PresentationModuleController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InternshipManagementSystem.Controllers
{
    [Authorize]
    public class PresentationModuleController : BaseController
    {
        String connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\user\Pictures\InMS\InternshipManagementSystem\App_Data\INMS.mdf;Integrated Security=True";
        // GET: PresentationModule
        public ActionResult PresentationScheduleCoView()
        {
            if(ViewBag.Role == "Student")
            {
                return RedirectToAction("PresentationScheduleStdView");
            }
            List<Models.UserModel> alldetails = new List<Models.UserModel>();
            alldetails = GetStudentDetails();
            return View(alldetails);
        }
        public List<Models.UserModel> GetStudentDetails()
        {
            Models.UserModel studentdetail = null;
            List<Models.UserModel> alldetails = new List<Models.UserModel>();
            int i;
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[User_Table] WHERE Roles = 'Student' ORDER BY Full_Name ASC", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                while (rd.Read())
                {
                    studentdetail = new Models.UserModel();
                    studentdetail.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    studentdetail.Username = Convert.ToString(rd.GetSqlValue(2));
                    studentdetail.FullName = Convert.ToString(rd.GetSqlValue(4));
                    studentdetail.MatricID = Convert.ToString(rd.GetSqlValue(5));
                    studentdetail.State = Convert.ToString(rd.GetSqlValue(8));
                    studentdetail.CompanyName = Convert.ToString(rd.GetSqlValue(9));
                    studentdetail.FacultySupervisorName = Convert.ToString(rd.GetSqlValue(12));
                    studentdetail.IndustrySupervisorName = Convert.ToString(rd.GetSqlValue(13));
                    studentdetail.InternshipPeriodStart = Convert.ToString(rd.GetSqlValue(16));
                    studentdetail.InternshipPeriodEnd = Convert.ToString(rd.GetSqlValue(17));
                    studentdetail.PresentationDate = Convert.ToString(rd.GetSqlValue(18));
                    studentdetail.PresentationTime = Convert.ToString(rd.GetSqlValue(19));
                    studentdetail.PresentationVenue = Convert.ToString(rd.GetSqlValue(20));
                    studentdetail.Accepted = Convert.ToString(rd.GetSqlValue(21));
                    alldetails.Add(studentdetail);
                }
            }
            return alldetails;
        }
        public ActionResult PresentationScheduleFormView(String id)
        {
            Models.UserModel model = new Models.UserModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[User_Table] WHERE Id = " + id , cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                rd.Read();
                model.Username = Convert.ToString(rd.GetSqlValue(2));
            }
            return View(model);
        }
        public ActionResult SetPresentationSchedule(Models.UserModel model)
        {
            String _sql = "";
            using (SqlConnection cn = new SqlConnection(connectionString))
            {

                _sql = "UPDATE [dbo].[User_Table] "
                        + "SET Presentation_Date = '" + model.PresentationDate
                        + "', Presentation_Time = '" + model.PresentationTime + "', Presentation_Venue ='"
                        + model.PresentationVenue + "', Accepted = 'Waiting for response' WHERE Username = '"
                        + model.Username + "'";
                SqlCommand cmd = new SqlCommand(_sql, cn);
                cn.Open();
                cmd.ExecuteNonQuery();
            }
            return RedirectToAction("PresentationScheduleCoView");
        }
        [Authorize]
        public ActionResult PresentationScheduleStdView()
        {
            Models.UserModel model = new Models.UserModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[User_Table] WHERE Username = '" + ViewBag.Username + "'", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                rd.Read();
                model.Username = Convert.ToString(rd.GetSqlValue(2));
                model.PresentationDate = Convert.ToString(rd.GetSqlValue(18));
                model.PresentationTime = Convert.ToString(rd.GetSqlValue(19));
                model.PresentationVenue = Convert.ToString(rd.GetSqlValue(20));
                model.Accepted = Convert.ToString(rd.GetSqlValue(21));
            }
            return View(model);
        }
        public ActionResult UpdateScheduleStatus (String username, String status)
        {
            String finalStatus;
            if(status == "reject")
            {
                finalStatus = "Rejected";
            }
            else
            {
                finalStatus = "Accepted";
            }
            String _sql = "";
            using (SqlConnection cn = new SqlConnection(connectionString))
            {

                _sql = "UPDATE [dbo].[User_Table] SET "
                        + "Accepted = '" + finalStatus  + "' WHERE Username = '"
                        + username + "'";
                SqlCommand cmd = new SqlCommand(_sql, cn);
                cn.Open();
                cmd.ExecuteNonQuery();
            }
            return RedirectToAction("PresentationScheduleStdView");

        }
    }
}

InternshipManagementSystem/Views/PresentationModule/PresentationScheduleCoView.cshtml
@model List<InternshipManagementSystem.Models.UserModel>
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    table, td, th {
        border: 1px solid #ddd;
        text-align: left;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 15px;
    }
</style>

    <!--//banner -->
    <!--/w3_short-->
    <div class="services-breadcrumb_w3layouts">
        <div class="inner_breadcrumb">

            <ul class="short_w3ls" _w3ls>
                <li><a href="index.html">Home</a><span>|</span></li>
                <li>Presentation Schedule</li>
            </ul>
        </div>
        <div class="tittle_head_w3ls">
            <h3 class="tittle three">Presentation Schedule</h3>
        </div>
    </div>
@Styles.Render("~/Content/viewlogbook.css")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>

    <h2>Presentation Schedule</h2>

    <table style="width:100%; border:2px solid black;">
        <thead style="display:block;">
            <tr>
                <th style="width:1%;text-align:center;">No</th>
                <th style="width:10%;text-align:center;">Matric ID</th>
                <th style="width:10%;text-align:center;">Name</th>
                <th style="width:10%;text-align:center;">Presentation Date</th>
                <th style="width:10%;text-align:center;">Presentation Venue</th>
                <th style="width:10%;text-align:center;">Status</th>
            </tr>
        </thead>
        <tbody style="display:block; height:300px;overflow-y:auto;overflow-x:hidden;width:100%; border-top:2px solid black;">
            @for (int i = 0; i < Model.Count; i++)
            {

                <tr>
                    <td style="width:2%;text-align:center;">@(i + 1)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(Model[i].MatricID)</td>
                    <td style="width:10%;text-align:center;">@Html.Raw(Model[i].FullName)</td>
                    @if (Model[i].Accepted == "Null")
                {
                        <td style="width:10%;text-align:center;">-</td>
                        <td style="width:10%;text-align:center;">-</td>
                        <td style="width:10%;text-align:center;">
                            @Html.ActionLink("Set Schedule", "PresentationScheduleFormView", "PresentationModule", new { @id = Model[i].Id }
                 , null)
                        </td>

                    }
                    else
                    {
                        <td style="width:10%;text-align:center;">@Html.Raw(Model[i].PresentationDate)</td>
                        <td style="width:10%;text-align:center;">@Html.Raw(Model[i].PresentationVenue)</td>
                        if (Model[i].Accepted == "Accepted")
                        {
                            <td style="width:10%;text-align:center;color:green"><label>@Html.Raw(Model[i].Accepted)</label></td>
                        }
                        else if (Model[i].Accepted == "Rejected")
                        {
                            <td style="width:10%;text-align:center;color:red"><label>@Html.Raw(Model[i].Accepted)</label>,&nbsp;@Html.ActionLink("Set Schedule", "PresentationScheduleFormView", "PresentationModule", new { @id = Model[i].Id }, null) </td>
                        }
                        else
                        {
                            <td style="width:10%;text-align:center;">@Html.Raw(Model[i].Accepted)</td>
                        }
                    }
                </tr>

            }
        </tbody>
    </table>
    <script>

        var $table = $('table.scroll'),
            $bodyCells = $table.find('tbody tr:first').children(),
            colWidth;

        // Adjust the width of thead cells when window resizes
        $(window).resize(function () {
            // Get the tbody columns width array
            colWidth = $bodyCells.map(function () {
                return $(this).width();
            }).get();

            // Set the width of thead columns
            $table.find('thead tr').children().each(function (i, v) {
                $(v).width(colWidth[i]);
            });
        }).resize();
    </script>
    <!-- //inner_content -->
    <!-- footer -->
   <div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

InternshipManagementSystem/Views/PresentationModule/PresentationScheduleFormView.cshtml
@model InternshipManagementSystem.Models.UserModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    table, td, th {
        border: 1px solid #ddd;
        text-align: left;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 15px;
    }
</style>

    <!--//banner -->
    <!--/w3_short-->
    <div class="services-breadcrumb_w3layouts">
        <div class="inner_breadcrumb">

            <ul class="short_w3ls" _w3ls>
                <li><a href="index.html">Home</a><span>|</span></li>
                <li>Presentation Schedule</li>
            </ul>
        </div>
    </div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Presentation Schedule</h3>
</div>
    <div class="container">
        <div class="col-lg-12 well">
            <div class="row">
                @using (Html.BeginForm("SetPresentationSchedule", "PresentationModule", FormMethod.Post))
                {
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-4 form-group" style="text-align:right;">
                                Calendar :
                            </div>
                            <div class="col-sm-8 form-group">
                                @Html.TextBoxFor(model => model.PresentationDate,
           new { required = "required", @type = "date", @Value = Model.PresentationDate })
                                @Html.HiddenFor(model => (model.Username))
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4 form-group" style="text-align:right;">
                                Time :
                            </div>
                            <div class="col-sm-8 form-group">
                                @Html.TextBoxFor(model => model.PresentationTime)
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4 form-group" style="text-align:right;">
                                Venue :
                            </div>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(model => (model.PresentationVenue))
                            </div>
                        </div>
                        <div class="row" style="text-align:center;">
                            <button style="margin-top: 20px;" type="submit" class="btn btn-lg btn-info">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- //inner_content -->
    <!-- footer -->
   <div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

InternshipManagementSystem/Views/PresentationModule/PresentationScheduleStdView.cshtml
@model InternshipManagementSystem.Models.UserModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    table, td, th {
        border: 1px solid #ddd;
        text-align: left;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 15px;
    }
</style>

 <!--//banner -->
<!--/w3_short-->

<div class="services-breadcrumb_w3layouts">
    <div class="inner_breadcrumb">

        <ul class="short_w3ls" _w3ls>
            <li><a @Html.ActionLink("Home", "Index", "Home")</a><span>|</span></li>
            <li>Presentation Schedule</li>
        </ul>
    </div>
</div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Presentation Schedule</h3>
</div>
<br />
@if (Model.Accepted == "Null")
{
    <div>No Presentation Schedule Yet!</div>
}
else
{ 
        <div class="container">
            <div class="col-lg-12 well">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-6 form-group" style="text-align:right;">
                                Calendar :
                            </div>
                            <div class="col-sm-6 form-group">
                                @Html.Label(Model.PresentationDate)
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 form-group" style="text-align:right;">
                                Time :
                            </div>
                            <div class="col-sm-6 form-group">
                                @Html.Label(Model.PresentationTime)
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 form-group" style="text-align:right;">
                                Venue :
                            </div>
                            <div class="col-sm-6">
                                @Html.Label(Model.PresentationVenue)
                                <input type="hidden" value="@ViewBag.Username" id="user" />
                            </div>
                        </div>
                        @if (Model.Accepted == "Waiting for response")
                        {
                            <div class="row" style="text-align:center;">
                                <div class="col-sm-6 form-group" style="text-align:right;">
                                    <input type="button" onclick="Accept()" value="Accept" />
                                </div>
                                <div class="col-sm-6 form-group" style="text-align:left;">
                                    <input type="button" onclick="Reject()" value="Reject" />
                                </div>
                            </div>

                        }
                        else if (Model.Accepted == "Rejected")
                        {
                            <div class="row" style="text-align:center; color:red;">REJECTED</div>
                        }
                        else if (Model.Accepted == "Accepted")
                        {
                            <div class="row" style="text-align:center; color:green;">ACCEPTED</div>
                        }
                    </div>
                </div>
            </div>
        </div>

        <script>
            function Accept() {
                var user = document.getElementById('user').value;
                window.location.href = '/PresentationModule/UpdateScheduleStatus?username=' + user + '&status=accept';
            }
            function Reject() {
                var user = document.getElementById('user').value;
                window.location.href = '/PresentationModule/UpdateScheduleStatus?username=' + user + '&status=reject';
            }
        </script>
}
<br />
        <!-- //inner_content -->
        <!-- footer -->

      <div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>