InternshipManagementSystem/Controllers/EvaluationModuleController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InternshipManagementSystem.Controllers
{
    [Authorize]
    public class EvaluationModuleController : BaseController
    {
        String connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\user\Pictures\InMS\InternshipManagementSystem\App_Data\INMS.mdf;Integrated Security=True";

        // GET: EvaluationModule
        [HttpGet]
        public ActionResult EvaluationSvView (String id)
        {
            List<Models.UserModel> users = null;
            List<Models.UserModel> foundUsers = new List<Models.UserModel>();
            users = Models.UserModel.SvGetUser(ViewBag.Username);
            if(ViewBag.Role == "Student")
            {
                return RedirectToAction("EvaluationStdView");
            }
            else if (ViewBag.Role == "Faculty Coordinator")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                ViewBag.found = false;
                return View(users);
            }
            id = id.ToLower();
            foreach (Models.UserModel model in users)
            {
                if (model.MatricID.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
                else if (model.FullName.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
                else if (model.CompanyName.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
                else if (model.State.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
            }
            if (foundUsers != null)
            {
                ViewBag.Found = true;
                return View(foundUsers);
            }
            else
            {
                ViewBag.Found = false;
                return View();
            }
        }
        public ActionResult LogbookEvaluation (String username)
        {
            if(username == null)
            {
                return RedirectToAction("EvaluationSvView");
            }
            Models.EvaluationModel evaluation = new Models.EvaluationModel();
            evaluation = GetLogbookEvaluation(username);
            evaluation.User = new Models.UserModel();
            evaluation.User = Models.UserModel.GetUserDetails(username);
            return View(evaluation);
        }
        public Models.EvaluationModel GetLogbookEvaluation (String username)
        {
            Models.EvaluationModel model = new Models.EvaluationModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Evaluation_Table] WHERE Type ='Logbook' AND Fk_username = '" + username + "' AND Evaluated_By ='" + ViewBag.Role + "'", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                if (rd.Read())
                {
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.Type = Convert.ToString(rd.GetSqlValue(1));
                    model.Fk_username = Convert.ToString(rd.GetSqlValue(2));
                    model.OptionA = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(3)));
                    model.OptionB = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(4)));
                    model.OptionC = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(5)));
                    if (model.Type == "Presentation") model.OptionD = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(6)));
                    model.Comment = Convert.ToString(rd.GetSqlValue(7));
                    model.EvaluatedBy = Convert.ToString(rd.GetSqlValue(8));

                }
            }
            return model;
        }
        public ActionResult EvaluateLogbook(Models.EvaluationModel model)
        {
            using(SqlConnection cn = new SqlConnection(connectionString))
            {
                String _sql = @"INSERT INTO [dbo].[Evaluation_Table] VALUES ('Logbook', '"
                + model.User.Username + "', " + model.OptionA + " , " + model.OptionB + " , "
                + model.OptionC + ", 0, '" + model.Comment + "', '" + model.EvaluatedBy + "')";
                var cmd = new SqlCommand(_sql, cn);
                cn.Open();
                cmd.ExecuteNonQuery();
            }
            return RedirectToAction("EvaluationSvView");
        }
        public ActionResult InternshipEvaluation (String username)
        {
            if(username == null)
            {
                return RedirectToAction("EvaluationSvView");
            }
            Models.EvaluationModel evaluation = new Models.EvaluationModel();
            evaluation = GetInternshipEvaluation(username);
            evaluation.User = new Models.UserModel();
            evaluation.User = Models.UserModel.GetUserDetails(username);
            return View(evaluation);
        }
        public Models.EvaluationModel GetInternshipEvaluation(String username)
        {
            Models.EvaluationModel model = new Models.EvaluationModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Evaluation_Table] WHERE Type ='Internship' AND Fk_username = '" + username + "' AND Evaluated_By ='" + ViewBag.Role + "'", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                if (rd.Read())
                {
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.Type = Convert.ToString(rd.GetSqlValue(1));
                    model.Fk_username = Convert.ToString(rd.GetSqlValue(2));
                    model.OptionA = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(3)));
                    model.OptionB = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(4)));
                    model.OptionC = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(5)));
                    model.Comment = Convert.ToString(rd.GetSqlValue(7));
                    model.EvaluatedBy = Convert.ToString(rd.GetSqlValue(8));

                }
            }
            return model;
        }
        public ActionResult EvaluateInternship(Models.EvaluationModel model)
        {
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                String _sql = @"INSERT INTO [dbo].[Evaluation_Table] VALUES ('Internship', '"
                + model.User.Username + "', " + model.OptionA + " , " + model.OptionB + " , "
                + model.OptionC + ", 0, '" + model.Comment + "', '" + model.EvaluatedBy + "')";
                var cmd = new SqlCommand(_sql, cn);
                cn.Open();
                cmd.ExecuteNonQuery();
            }
            return RedirectToAction("EvaluationSvView");

        }
        public ActionResult PresentationEvaluation(String username)
        {
            if (username == null)
            {
                return RedirectToAction("EvaluationSvView");
            }
            Models.EvaluationModel evaluation = new Models.EvaluationModel();
            evaluation = GetPresentationEvaluation(username);
            evaluation.User = new Models.UserModel();
            evaluation.User = Models.UserModel.GetUserDetails(username);
            return View(evaluation);
        }
        public Models.EvaluationModel GetPresentationEvaluation(String username)
        {
            Models.EvaluationModel model = new Models.EvaluationModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Evaluation_Table] WHERE Type ='Presentation' AND Fk_username = '" + username + "' AND Evaluated_By ='" + ViewBag.Role + "'", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                if (rd.Read())
                {
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.Type = Convert.ToString(rd.GetSqlValue(1));
                    model.Fk_username = Convert.ToString(rd.GetSqlValue(2));
                    model.OptionA = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(3)));
                    model.OptionB = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(4)));
                    model.OptionC = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(5)));
                    model.OptionD = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(6)));
                    model.Comment = Convert.ToString(rd.GetSqlValue(7));
                    model.EvaluatedBy = Convert.ToString(rd.GetSqlValue(8));
                }
            }
            return model;
        }
        public ActionResult EvaluatePresentation(Models.EvaluationModel model)
        {
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                String _sql = @"INSERT INTO [dbo].[Evaluation_Table] VALUES ('Presentation', '"
                + model.User.Username + "', " + model.OptionA + " , " + model.OptionB + " , "
                + model.OptionC + ", 0, '" + model.Comment + "', '" + model.EvaluatedBy + "')";
                var cmd = new SqlCommand(_sql, cn);
                cn.Open();
                cmd.ExecuteNonQuery();
            }
            return RedirectToAction("EvaluationSvView");

        }
        public ActionResult EvaluationStdView()
        {
            List<Models.EvaluationModel> list = new List<Models.EvaluationModel>();
            Models.EvaluationModel model = null;

InternshipManagementSystem/Controllers/LogbookModuleController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InternshipManagementSystem.Controllers
{
    [Authorize]
    public class LogbookModuleController : BaseController
    {
        String connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\user\Pictures\InMS\InternshipManagementSystem\App_Data\INMS.mdf;Integrated Security=True";

        // GET: LogbookModule
        public ActionResult LogbookStd()
        {
            if (!User.IsInRole("Student"))
            {
                return RedirectToAction("LogbookSv");
            }
            String username = ViewBag.Username;
            Models.UserModel user = Models.UserModel.GetUserDetails(username);
            List<Models.LogbookModel> logbooks = null;
            logbooks = Models.LogbookModel.GetLogbookList(username);
            dynamic mymodel = new ExpandoObject();
            mymodel.User = user;
            mymodel.Logbooks = logbooks;
            return View(mymodel);
        }
        public ActionResult ViewLogbookStd(int id)
        {
            Models.LogbookModel model = new Models.LogbookModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Logbook_Table] " +
                    "WHERE Id = " + id, cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                while (rd.Read())
                {
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.AuthorUsername = Convert.ToString(rd.GetSqlValue(1));
                    model.Datetime = Convert.ToDateTime(Convert.ToString(rd.GetSqlValue(2)));
                    model.Title = Convert.ToString(rd.GetSqlValue(3));
                    model.Description = Convert.ToString(rd.GetSqlValue(4));
                    model.Week = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(5)));
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult CreateNewLogbook(int? id)
        {
            if(ViewBag.Role != "Student")
            {
                return RedirectToAction("LogbookSvView");
            }
            if (id == null)
            {
                return View();
            }

            Models.LogbookModel model = new Models.LogbookModel();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Logbook_Table] " +
                    "WHERE Id = " + id, cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                while (rd.Read())
                {
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.AuthorUsername = Convert.ToString(rd.GetSqlValue(1));
                    model.Datetime = Convert.ToDateTime(Convert.ToString(rd.GetSqlValue(2)));
                    model.Title = Convert.ToString(rd.GetSqlValue(3));
                    model.Description = Convert.ToString(rd.GetSqlValue(4));
                    model.Week = Convert.ToInt32(Convert.ToString(rd.GetSqlValue(5)));
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateNewLogbook(Models.LogbookModel model)
        {
            if (SaveLogbook(model))
            {
                return RedirectToAction("LogbookStd");
            }
            return View(model);
        }

        public bool SaveLogbook(Models.LogbookModel model)
        {
            String _sql = "";
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                model.AuthorUsername = ViewBag.Username;
                int? id = model.Id;
                if (id == 0)
                {
                    _sql = "INSERT INTO [dbo].[Logbook_Table] VALUES ('"
                        + model.AuthorUsername + "', '" + model.Datetime + "', '"
                        + model.Title + "', '" + model.Description + "', " + model.Week
                        + ")";
                }
                else
                {
                    _sql = "UPDATE [dbo].[Logbook_Table] "
                        + "SET Datetime = '" + model.Datetime
                        + "', Title = '" + model.Title + "', Description = '"
                        + model.Description + "', Week = " + model.Week + " WHERE Id = "
                        + Convert.ToString(model.Id);
                }
                SqlCommand cmd = new SqlCommand(_sql, cn);
                cn.Open();
                try
                {
                    cmd.ExecuteNonQuery();
                }
                catch (Exception)
                {
                    return false;
                }
                return true;
            }
        }

        [HttpGet]
        public ActionResult LogBookSv(String id)
        {
            List<Models.UserModel> users = null;
            List<Models.UserModel> foundUsers = new List<Models.UserModel>();
            if (ViewBag.Role == "Faculty Coordinator")
            {
                users = Models.UserModel.GetAllUser();
            }
            else if (ViewBag.Role == "Faculty Supervisor" || ViewBag.Role == "Industrial Supervisor")
            {
                users = Models.UserModel.SvGetUser(ViewBag.Username);
            }
            else return RedirectToAction("LogbookStd");
            dynamic mymodel = new ExpandoObject();

            if (id == null)
            {
                ViewBag.found = false;
                return View(users);
            }
            id = id.ToLower();
            foreach (Models.UserModel model in users)
            {
                if (model.MatricID.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
                else if (model.FullName.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
                else if (model.CompanyName.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
                else if (model.State.ToLower().Contains(id))
                {
                    foundUsers.Add(model);
                }
            }
            if (foundUsers != null)
            {
                ViewBag.Found = true;
                mymodel.Users = foundUsers;
                return View(mymodel);
            }
            else
            {
                ViewBag.Found = false;
                return View();
            }
        }

        public PartialViewResult ViewPartial(String username)
        {
            Models.UserModel user = Models.UserModel.GetUserDetails(username);
            List<Models.LogbookModel> logbooks = null;
            logbooks = Models.LogbookModel.GetLogbookList(username);
            dynamic mymodel = new ExpandoObject();
            mymodel.User = user;
            mymodel.Logbooks = logbooks;
            return PartialView("ViewPartial",mymodel);
        }
        [HttpGet]
        public ActionResult ViewStudentLogbook(String username)
        {
            Models.UserModel user = Models.UserModel.GetUserDetails(username);
            List<Models.LogbookModel> logbooks = null;
            logbooks = Models.LogbookModel.GetLogbookList(username);
            dynamic mymodel = new ExpandoObject();
            mymodel.User = user;
            mymodel.Logbooks = logbooks;
            return View(mymodel);

        }
    }
}

InternshipManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Internship Management System | :: </title>
    <!--/tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!--//tags -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />

    <link href="~/Content/font-awesome.css" rel="stylesheet">
    <!-- //for bootstrap working -->
    <link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
          rel='stylesheet' type='text/css'>
</head>
<body>
    <!-- header -->
    <div class="header" id="home">
        <div class="content white agile-info">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="Index.cshtml">
                            <h1><span class="" aria-hidden="true"></span> InMs <label>Future Tech</label></h1>
                        </a>
                    </div>
                    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                        <nav class="link-effect-2" id="link-effect-2">
                            <ul class="nav navbar-nav">
                                <li class="active">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("Logbook", "LogbookStd", "LogbookModule")</li>
                                <li>@Html.ActionLink("Evaluation", "EvaluationSvView", "EvaluationModule")</li>
                                <li>@Html.ActionLink("Assign Supervisor", "AssignSupervisorView", "FacultyCoordinatorModule")</li>
                                <li>@Html.ActionLink("Presentation Schedule", "PresentationScheduleCoView", "PresentationModule")</li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle effect-3" arua-haspopup="true" aria-expanded="true" data-toggle="dropdown">Activities<b class="caret"></b></a>
                                    <ul class="dropdown-menu .pull-right">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <ul class="multi-column-dropdown">
                                                    <li>@Html.ActionLink("Announcement", "AnnouncementView", "GeneralActivityModule")</li>
                                                    <li>@Html.ActionLink("Private Message", "NewPrivateMessageView", "GeneralActivityModule")</li>
                                                    <li>@Html.ActionLink("FAQ Details", "FAQView", "GeneralActivityModule")</li>
                                                    <li>@Html.ActionLink("Internship Report", "StdReportView", "GeneralActivityModule")</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </ul>
                                </li>
                                <li>@Html.ActionLink("Logout", "Logout", "UserModule")</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>