InternshipManagementSystem/Controllers/GeneralActivityModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Data;
using System.Web.Security;

namespace InternshipManagementSystem.Controllers
{
    [Authorize]
    public class GeneralActivityModuleController : BaseController
    {
        String connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\user\Pictures\InMS\InternshipManagementSystem\App_Data\INMS.mdf;Integrated Security=True";
        // GET: GeneralActivityModule
        [HttpGet]
        public ActionResult AnnouncementView(String id)
        {
            List<Models.AnnouncementModel> announcements = new List<Models.AnnouncementModel>();
            List<Models.AnnouncementModel> foundAnnouncements = null;
            announcements = getAnnouncement();
            if (id == null)
            {
                ViewBag.Found = true;
                return View(announcements);
            }
            else
            {
                id = id.ToLower();
                foreach (Models.AnnouncementModel model in announcements)
                {
                    if (model.Content.ToLower().Contains(id))
                    {
                        if (foundAnnouncements == null)
                        {
                            foundAnnouncements = new List<Models.AnnouncementModel>();
                        }
                        foundAnnouncements.Add(model);
                    }
                    else if (model.Title.ToLower().Contains(id))
                    {
                        if (foundAnnouncements == null)
                        {
                            foundAnnouncements = new List<Models.AnnouncementModel>();
                        }
                        foundAnnouncements.Add(model);
                    }
                }
                if (foundAnnouncements != null)
                {
                    ViewBag.Found = true;
                    return View(foundAnnouncements);
                }
                else
                {
                    ViewBag.Found = false;
                    return View();
                }
            }
        }

        public List<Models.AnnouncementModel> getAnnouncement()
        {
            Models.AnnouncementModel model = null;
            List<Models.AnnouncementModel> announcements = new List<Models.AnnouncementModel>();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Announcement_Table] ORDER BY Datetime DESC", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();

                while (rd.Read())
                {
                    model = new Models.AnnouncementModel();
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.Content = Convert.ToString(rd.GetSqlValue(1));
                    model.Datetime = Convert.ToDateTime(Convert.ToString(rd.GetSqlValue(2)));
                    model.AuthorName = Convert.ToString(rd.GetSqlValue(3));
                    model.Category = Convert.ToString(rd.GetSqlValue(4));
                    model.Title = Convert.ToString(rd.GetSqlValue(5));
                    announcements.Add(model);
                }
            }
            return announcements;
        }
        [HttpGet]
        [Authorize(Roles = "Faculty Coordinator")]
        public ActionResult AnnouncementFormView(int? id)
        {
            if (id == null)
            {
                ViewBag.Action = "";
                return View();
            }
            else
            {
                Models.AnnouncementModel model = null;
                using (SqlConnection cn = new SqlConnection(connectionString))
                {
                    SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[Announcement_Table] WHERE Id = " + Convert.ToString(id), cn);
                    cn.Open();
                    SqlDataReader rd = cmd.ExecuteReader();
                    while (rd.Read())
                    {
                        model = new Models.AnnouncementModel();
                        model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                        model.Content = Convert.ToString(rd.GetSqlValue(1));
                        model.Content = model.Content.Replace("<br />", "\r\n");
                        model.Datetime = Convert.ToDateTime(Convert.ToString(rd.GetSqlValue(2)));
                        model.AuthorName = Convert.ToString(rd.GetSqlValue(3));
                        model.Category = Convert.ToString(rd.GetSqlValue(4));
                        model.Title = Convert.ToString(rd.GetSqlValue(5));
                    }
                }
                ViewBag.Action = "Edit";
                return View(model);
            }
        }
        [HttpPost]
        [Authorize(Roles = "Faculty Coordinator")]
        public ActionResult AnnouncementFormView(Models.AnnouncementModel model)
        {
            if (SaveAnnouncement(model))
            {
                return RedirectToAction("AnnouncementView");
            }
            return View(model);
        }
        [Authorize(Roles = "Faculty Coordinator")]
        public ActionResult DeleteAnnouncement(int id)
        {
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("DELETE FROM [dbo].[Announcement_Table] "
                    + "WHERE Id = " + Convert.ToString(id), cn);
                cn.Open();
                cmd.ExecuteNonQuery();
                return RedirectToAction("AnnouncementView");
            }

        }
        [Authorize(Roles = "Faculty Coordinator")]
        public bool SaveAnnouncement(Models.AnnouncementModel model)
        {
            String _sql = "";
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                model.AuthorName = ViewBag.Username;
                model.Datetime = DateTime.Now;
                model.Content = model.Content.Replace("\r\n", "<br />");
                int? id = model.Id;
                if (id == 0)
                {
                    _sql = @"INSERT INTO [dbo].[Announcement_Table] VALUES ('"
                        + model.Content + "', '" + Convert.ToString(model.Datetime) + "', '"
                        + model.AuthorName + "', '" + model.Category + "', '"
                        + model.Title + "')";
                }
                else
                {
                    _sql = @"UPDATE [dbo].[Announcement_Table] "
                        + "SET Contents = '" + model.Content
                        + "', Title = '" + model.Title + "', Category ='"
                        + model.Category + "' WHERE Id = "
                        + Convert.ToString(model.Id);
                }
                SqlCommand cmd = new SqlCommand(_sql, cn);
                cn.Open();
                try
                {
                   
                }
                catch (Exception)
                {
                    return false;
                }
                return true;
            }
        }
        [HttpGet]
        public ActionResult FAQView(String id)
        {
            List<Models.FAQModel> FAQs = new List<Models.FAQModel>();
            List<Models.FAQModel> foundFAQs = null;
            FAQs = GetFAQ();
            if (id == null)
            {
                ViewBag.Found = true;
                return View(FAQs);
            }
            else
            {
                id = id.ToLower();
                foreach (Models.FAQModel model in FAQs)
                {
                    if (model.Question.ToLower().Contains(id))
                    {
                        if (foundFAQs == null)
                        {
                            foundFAQs = new List<Models.FAQModel>();
                        }
                        foundFAQs.Add(model);
                    }
                    else if (model.Answer.ToLower().Contains(id))
                    {
                        if (foundFAQs == null)
                        {
                            foundFAQs = new List<Models.FAQModel>();
                        }
                        foundFAQs.Add(model);
                    }
                }
                if (foundFAQs != null)
                {
                    ViewBag.Found = true;
                    return View(foundFAQs);
                }
                else
                {
                    ViewBag.Found = false;
                    return View();
                }
            }
        }
        public List<Models.FAQModel> GetFAQ()
        {
            Models.FAQModel model = null;
            List<Models.FAQModel> FAQs = new List<Models.FAQModel>();
            using (SqlConnection cn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM [dbo].[FAQ_Table]", cn);
                cn.Open();
                SqlDataReader rd = cmd.ExecuteReader();
                while (rd.Read())
                {
                    model = new Models.FAQModel();
                    model.Id = Int32.Parse(Convert.ToString(rd.GetSqlValue(0)));
                    model.Question = Convert.ToString(rd.GetSqlValue(1));
                    model.Answer = Convert.ToString(rd.GetSqlValue(2));
                    model.Datetime = Convert.ToDateTime(Convert.ToString(rd.GetSqlValue(3)));
                    model.AuthorUsername = Convert.ToString(rd.GetSqlValue(4));
                    FAQs.Add(model);
                }
            }
            return FAQs;
        }
        [HttpGet]
        [Authorize(Roles = "Faculty Coordinator")]
        public ActionResult FAQFormView(int? id)
        {
            if (id == null)
            {

InternshipManagementSystem/Views/GeneralActivityModule/AnnouncementFormView.cshtml
@model InternshipManagementSystem.Models.AnnouncementModel

@{
    ViewBag.Title = "AnnouncementFormView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--//banner -->
<!--/w3_short-->
<div class="services-breadcrumb_w3layouts">
    <div class="inner_breadcrumb">

        <ul class="short_w3ls" _w3ls>
            <li><a href="index.html">Home</a><span>|</span></li>
            <li>Announcement</li>
        </ul>
    </div>
</div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Announcement</h3>
</div>
<script>
    function validateCategory() {
        var category = document.getElementById("category");
        var text = category.options[category.selectedIndex].value;
        if (text == "") {
            return false;
        }
        else {
            return true;
        }
    }
</script>
@if (ViewBag.Action == "Edit")
{
    <h2>Edit Announcement</h2>
}
else
{
    <h2>Add New Announcement</h2>
}
<div class="container">
    <div class="col-lg-12 well">
        <div class="row">
            @{
                var listItems = new List<SelectListItem>()
                {
                    new SelectListItem {Text = "Important", Value = "Important"},
                    new SelectListItem {Text = "Normal", Value = "Normal"}
                };
            }
            @using (Html.BeginForm("AnnouncementFormView", "GeneralActivityModule", FormMethod.Post, new { onsubmit = "return validateCategory()" }))
            {
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right;">
                            Title :
                        </div>
                        <div class="col-sm-8 form-group">
                            @Html.TextBoxFor(model => (model.Title), new { style = "width: 100%;" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right;">
                            Category :
                        </div>
                        <div class="col-sm-8 form-group">
                            @Html.DropDownListFor(model => (model.Category), listItems,
                                      "Select Category", new { @id = "category" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right;">
                            Description :
                        </div>
                        <div class="col-sm-8">
                            @Html.TextAreaFor(model => (model.Content), 5, 60, null)
                        </div>
                    </div>
                    <div class="row" style="text-align:center;">
                        @Html.HiddenFor(model => (model.Id))
                        <button style="margin-top: 20px;" type="submit" class="btn btn-lg btn-info">Submit</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<!-- //inner_content -->
<!-- footer -->
<div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

InternshipManagementSystem/Views/GeneralActivityModule/AnnouncementView.cshtml
@model List<InternshipManagementSystem.Models.AnnouncementModel>

@{
    ViewBag.Title = "Announcements";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @if (ViewBag.Role == "Faculty Coordinator")
    {
        @Html.ActionLink("Create New", "AnnouncementFormView")
    }
</p>
<div class="services-breadcrumb_w3layouts">
    <div class="inner_breadcrumb">

        <ul class="short_w3ls" _w3ls>
            <li><a href="index.html">Home</a><span>|</span></li>
            <li>Announcement</li>
        </ul>
    </div>
</div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Announcement</h3>
</div>
<style>
    input[type=search] {
         width: 130px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image: url('searchicon.png');
    background-position: 10px 10px; 
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
}

input[type=search]:focus {
    width: 100%;
}
</style>
<div style="width: 100%; text-align:center; display:block; margin-bottom: 20px;">
    <input type="search" id="txtSearch" placeholder="Search.." /><input type="button" id="btnSearch" class="btn btn-lg btn-info" value="Search" onclick="StartSearch();" />
    <br />
</div>

<script>
    function StartSearch() {
        var Text = document.getElementById('txtSearch').value;
        window.location.href = '/GeneralActivityModule/AnnouncementView/' + Text;
    }
</script>
<div id="scrolldiv" style="width:100%; height:400px; overflow-x:hidden; overflow:auto;">
    <table class="table">
        
        @if (ViewBag.Found == true)
        {
            foreach (var item in Model)
            {
            <tr>
                <td>
                    <div style="display: inline-block; font-size:medium; text-decoration:solid;">
                        @Html.Label(item.Title) 
                    </div>
                    @if (item.Category == "Important")
                    {
                        <label style="display: inline-block; font-size:10px; text-decoration:solid; color:red; vertical-align:top" >
                            *IMPORTANT
                        </label>
                    }
                    <div style="display:inline-block; float: right;">
                        @Html.Label(Convert.ToString(item.Datetime))
                    </div>
                    <br />
                    <div>@Html.Raw(item.Content)</div>
                    <div style="float: right;">
                        @if (ViewBag.Role == "Faculty Coordinator")
                        {
                            @Html.ActionLink("Edit", "AnnouncementFormView",
                  "GeneralActivityModule", new { item.Id }, new { })
                            <div style="display:inline-block;"> | </div>
                            @Html.ActionLink("Delete", "DeleteAnnouncement",
                  "GeneralActivityModule", new { @id = item.Id },
                  new { onclick = "return confirm ('Are you sure you wish to delete this announcement?');" })
                        }
                    </div>
                </td>
            </tr>

            }
        }
        else
        {
            <tr>
                <td>Not Found!</td>
            </tr>
        }

    </table>
</div>
<div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

InternshipManagementSystem/Views/GeneralActivityModule/FAQFormView.cshtml
@model InternshipManagementSystem.Models.FAQModel

@{
    ViewBag.Title = "FAQFormView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.Action == "Edit")
{
    <h2>Edit FAQ</h2>
}
else
{
    <h2>Add New FAQ</h2>
}

<!--//banner -->
<!--/w3_short-->
<div class="services-breadcrumb_w3layouts">
    <div class="inner_breadcrumb">

        <ul class="short_w3ls" _w3ls>
            <li><a href="index.html">Home</a><span>|</span></li>
            <li>Frequently Asked Question</li>
        </ul>
    </div>
</div>
<div class="tittle_head_w3ls">
    <h3 class="tittle three">Frequently Asked Question</h3>
</div>
<div class="container">
    <div class="col-lg-12 well">
        <div class="row">
            @using (Html.BeginForm("FAQFormView", "GeneralActivityModule", FormMethod.Post, new { }))
            {
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right;">
                            Question :
                        </div>
                        <div class="col-sm-8 form-group">
                            @Html.TextAreaFor(model => (model.Question), 3, 60, null)
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 form-group" style="text-align:right;">
                            Answer :
                        </div>
                        <div class="col-sm-8 form-group">
                            @Html.TextAreaFor(model => (model.Answer), 5, 60, null)
                        </div>
                    </div>
                    <div class="row" style="text-align:center;">
                        @Html.HiddenFor(model => (model.Id))
                        <button style="margin-top: 20px;" type="submit" class="btn btn-lg btn-info">Submit</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<!-- //inner_content -->
<!-- footer -->
<div class="footer_top_agileits">
    <div class="container">
        <div class="col-md-4 footer_grid">
            <h3>About Us</h3>
            <p>
                The main goal of the Internship Management System (InMS) is to manage and monitor the Internship’s student for students in University Malaysia Pahang during their internship duration efficiently.
            </p>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Latest News</h3>
            <ul class="footer_grid_list">
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Last Submission date for Internship Student on 31/12/2018</a>
                </li>
                <li>
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    <a href="single.html">Register with us.</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 footer_grid">
            <h3>Contact Info</h3>
            <ul class="address">
                <li><i class="fa fa-map-marker" aria-hidden="true"></i>No 1/100, Jalan Yang Benar, <span>Malaysia.</span></li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:futuretech@gmail.com">futuretech@gmail.com</a></li>
                <li><i class="fa fa-phone" aria-hidden="true"></i>+6011-22334455</li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                <div class="footer_bottom1">
                    <a>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <h2><span class="fa fa-signal" aria-hidden="true"></span> InMs <label>Future Tech</label></h2>
                    </a>
                    <p>© 2017 FutureTech. All rights reserved</a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>